# Clyde Configuration
version: 1.0

# Project metadata
project:
  name: "clyde"
  type: "application"  # api, web, cli, library
  language: "python"  # python, javascript, typescript
  framework: "" # fastapi, react, nextjs, etc.

# Module inclusions
includes:
  # Core principles (recommended for all projects)
  - core.*
  
  # Tool modules (recommended for all projects)
  - tools.*
  
  # Language-specific modules (uncomment as needed)

  - languages.python.general
  - languages.python.testing

  
  # Database modules (uncomment as needed)
  # - databases.postgres
  # - databases.mongodb

# Custom module paths (for project-specific modules)
custom_modules:
  # - path: .clyde/custom/my-patterns.md
  #   name: custom.my-patterns

# Configuration options
options:
  # Include module boundaries in generated file
  show_module_boundaries: true
  
  # Include table of contents
  include_toc: true
  
  # Validation level (strict, normal, permissive)  
  validation_level: "normal"
  
  # File splitting options
  max_tokens_per_file: 20000
  split_strategy: "includes"