# Claude Development Environment

**🚨 CRITICAL: Read configuration files BEFORE any work**

MANDATORY: Before responding to ANY request, you MUST read these files in order:

1. **`.clyde/generated-claude.md`** - Main coordination file (read this first)
2. **Read ALL files referenced** in the generated-claude.md file 
3. **`.clyde/project-claude.md`** - Project-specific instructions
4. **`.clyde/architecture.md`** - Project organization

**IMPORTANT:** The generated-claude.md file will list additional files you must read. Read each one using the Read tool. These files contain ALL team standards and override any defaults. They are AUTHORITATIVE.

## Configuration Management

- To update team standards: Edit `.clyde/config.yaml` and run `clyde sync`
- To add project-specific rules: Edit `.clyde/project-claude.md`
- Generated files are marked with timestamps and should not be hand-edited

## Quick Commands

```bash
# Sync configuration (rebuild generated.md from current config)
clyde sync

# Add a new module
clyde sync --add react.patterns

# Remove a module  
clyde sync --remove docker

# Check what would change
clyde sync --check
```

---
*Generated by clyde - Development Environment Configuration System*