# Gemini Development Environment

This project uses a modular configuration system managed by Clyde.

## Context Files
The following files extend this configuration:
@./.clyde/generated-gemini.md
@./.clyde/project-gemini.md
@./.clyde/architecture.md

## Configuration Management
- To update team standards: Edit `.clyde/config.yaml` and run `clyde sync`
- To add project-specific rules: Edit `.clyde/project-gemini.md`
- Generated files are marked with timestamps and should not be hand-edited

## Quick Commands

```bash
# Sync configuration (rebuild generated files from current config)
clyde sync

# Sync only Gemini target
clyde sync --target gemini

# Add a new module
clyde sync --add react.patterns

# Remove a module  
clyde sync --remove docker

# Check what would change
clyde sync --check
```

---
*Generated by clyde - Development Environment Configuration System*